apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: event-reporter-metrics
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: event-reporter-metrics
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8089
    targetPort: 8089
  selector:
    app.kubernetes.io/name: event-reporter
