name: test-github-actions

on:
  push:
    branches:
      - sync-*
  pull_request:
    branches:
      - sync-*
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  set-vars:
    permissions:
      contents: read
    if: github.repository == 'codefresh-io/argo-cd'
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.image-pr.outputs.tag }}
      platforms: ${{ steps.platforms.outputs.platforms }}
    steps:
      - uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # v4.0.0

      - name: Set image tag (push to feature branch)
        if: ${{ github.repository == 'codefresh-io/argo-cd' && github.event_name == 'pull_request' }}
        run: |
          CLEAN_REF=$(echo "${{ github.head_ref }}" | sed 's|^refs/[^/]*||; s|/|_|g')
          echo "tag=v$(cat ./VERSION)-${CLEAN_REF}-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        id: image-pr

      - name: Set image tag (push to sync-* branch)
        if: ${{ github.repository == 'codefresh-io/argo-cd' && github.event_name == 'push' }}
        run: echo "tag=v$(cat ./VERSION)-$(date +%Y-%m-%d)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        id: image-push
